FROM node:18-alpine AS builder

ARG APP_BACKEND_HOST
ENV APP_BACKEND_HOST=$APP_BACKEND_HOST

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
