services:
  frontend:
    build: 
      context: ./frontend
      args:
        - NODE_ENV=development
        - APP_BACKEND_HOST=backend:5000
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
