name: Build and Push Docker images

on:
  push:
    tags: [ v*.*.* ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - frontend
          - backend
    steps:
      - uses: actions/checkout@v3

      - name: Get Short SHA
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VERSION=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV
          else
            echo "VERSION=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/bake-action@v6
        with:
          targets: |
            ${{ matrix.target }}
          files: ./docker-bake.hcl
          set: |
            ${{ matrix.target }}.args.VERSION=$VERSION
          push: true
